config/urls.py
from django.conf.urls.static import static
from django.conf import settings
from django.contrib import admin
from django.urls import path, include

import user

urlpatterns = [
    path('admin/', admin.site.urls),
    path('apelsin/', include('shop.urls'), name='shop'),
    path('user/', include('user.urls'), name='user'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

shop/urls.py
from django.urls import path, include
from shop import views

app_name = 'shop'


urlpatterns = [
    path('', views.IndexView.as_view(), name='products'),
    path('detail/<int:pk>/', views.ProductDetailView.as_view(), name='product_detail'),
    path('category-detail/<int:category_id>/', views.IndexView.as_view(), name='products_of_category'),
    path('order-detail/<int:pk>/save/', views.OrderDetailView.as_view(), name = 'order_detail'),
    path('create-product/', views.ProductCreateView.as_view(), name='product_create'),
    path('delete-product/<int:pk>/', views.ProductDeleteView.as_view(), name='product_delete'),
    path('edit-product/<int:pk>/', views.ProductEditView.as_view(), name='product_edit'),
    path('product-comments/<int:pk>/', views.CommentView.as_view(), name='comment_view'),
]

user/urls.py
from django.urls import path, include
from user import views

app_name = 'user'

urlpatterns = [
    path('login-oauth-page', views.login_page, name='login_page'),
    path('logount/', views.login_page, name='logout_page'),
]

shop/models.py
from tkinter.constants import CASCADE

from django.db import models
from decimal import Decimal
from phonenumber_field.modelfields import PhoneNumberField



# Create your models here.


class BaseModel(models.Model):
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    my_order = models.PositiveIntegerField(default=0, blank=False, null=True)

    class Meta:
        ordering = ['my_order']
        abstract = True


class Category(BaseModel):
    title = models.CharField(max_length=100, unique=True)

    def __str__(self):
        return self.title

    class Meta:
        ordering = ['my_order']
        verbose_name = 'Category'
        verbose_name_plural = 'Categories'


class Product(BaseModel):

    class RatingChoise(models.IntegerChoices):
        ONE = 1
        TWO = 2
        THREE = 3
        FOUR = 4
        FIVE = 5

    name = models.CharField(max_length=255)
    description = models.TextField(null=True, blank=True)
    price = models.DecimalField(max_digits=14, decimal_places=2)
    discount = models.PositiveIntegerField(default=0)
    image = models.ImageField(upload_to='media/product/')
    category = models.ForeignKey(Category, on_delete=models.SET_NULL, related_name='products', null=True, blank=True)
    quantity = models.PositiveIntegerField(default=1, null=True, blank=True)
    rating = models.PositiveIntegerField(choices=RatingChoise.choices, default=RatingChoise.FIVE.value)


    @property
    def get_absolute_url(self):
        return self.image.url

    @property
    def discounted_price(self):
        if self.discount > 0:
            self.price = Decimal(self.price)*Decimal(1-self.discount / 100)
        return Decimal(self.price).quantize(Decimal('0.001'))

    def __str__(self):
        return self.name

    class Meta:
        ordering = ['my_order']
        verbose_name = 'Product'
        verbose_name_plural = 'Products'


class Order(BaseModel):
    full_name = models.CharField(max_length=255, null=True, blank=True)
    phone_number = PhoneNumberField(region="UZ")
    quantity = models.PositiveIntegerField(default=1)
    product = models.ForeignKey(Product, on_delete=models.SET_NULL, null=True, blank=True)

    def __str__(self):
        return f'{self.full_name} => {self.phone_number}'


class Comment(BaseModel):
    name = models.CharField(max_length=255, null=True, blank=True)
    email = models.EmailField()
    content = models.TextField()
    product = models.ForeignKey(Product, on_delete=models.CASCADE, related_name='comments', null=True, blank=True)

    is_negative = models.BooleanField(default=False)

    def __str__(self):
        return f"{self.name} => {self.created_at}"

    class Meta:
        ordering = ['my_order']
        #verbose_name = 'comment'

shop/forms.py
from django import forms
from phonenumber_field.modelfields import PhoneNumberField

from shop.models import Comment, Product


class OrderForm(forms.Form):
    full_name = forms.CharField()
    phone_number = PhoneNumberField(region='UZ')
    quantity = forms.IntegerField()


class ProductModelForm(forms.ModelForm):
    class Meta:
        model = Product
        fields = '__all__'
        # exclude = ()

class CommentModelForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = '__all__'

shop/views.py
from itertools import product
from lib2to3.fixes.fix_input import context
from typing import Optional

from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import render, get_object_or_404, redirect
from django.views import View

from shop.models import Product, Order, Category, Comment
from shop.forms import OrderForm, CommentModelForm, ProductModelForm


# Create your views here.
class IndexView(View):

    def get(self, request, category_id: Optional[int] = None, *args, **kwargs):
        search_query = request.GET.get('q', '')
        filter_type = request.GET.get('filter', '')
        categories = Category.objects.all()
        if category_id:
            if filter_type == 'expensive':
                products = Product.objects.filter(category_id=category_id).order_by('-price')
            elif filter_type == 'cheap':
                products = Product.objects.filter(category_id=category_id).order_by('price')
            elif filter_type == 'rating':
                products = Product.objects.filter(category_id=category_id, rating__gte=4).order_by('-rating')

            else:
                products = Product.objects.filter(category_id=category_id)

        else:
            if filter_type == 'expensive':
                products = Product.objects.all().order_by('-price')
            elif filter_type == 'cheap':
                products = Product.objects.all().order_by('price')
            elif filter_type == 'rating':
                products = Product.objects.filter(rating__gte=3).order_by('-rating')

            else:
                products = Product.objects.all()

        if search_query:
            products = Product.objects.filter(name__icontains=search_query)

        context = {
            'products': products,
            'categories': categories,
        }
        return render(request, 'shop/index.html', context=context)

# def index(request, category_id: Optional[int] = None):
#     search_query = request.GET.get('q', '')
#     filter_type = request.GET.get('filter', '')
#     categories = Category.objects.all()
#     if category_id:
#         if filter_type == 'expensive':
#             products = Product.objects.filter(category_id=category_id).order_by('-price')
#         elif filter_type == 'cheap':
#             products = Product.objects.filter(category_id=category_id).order_by('price')
#         elif filter_type == 'rating':
#             products = Product.objects.filter(category_id=category_id, rating__gte=4).order_by('-rating')
#
#         else:
#             products = Product.objects.filter(category_id=category_id)
#
#     else:
#         if filter_type == 'expensive':
#             products = Product.objects.all().order_by('-price')
#         elif filter_type == 'cheap':
#             products = Product.objects.all().order_by('price')
#         elif filter_type == 'rating':
#             products = Product.objects.filter(rating__gte=3).order_by('-rating')
#
#         else:
#             products = Product.objects.all()
#
#     if search_query:
#         products = Product.objects.filter(name__icontains=search_query)
#
#
#     context = {
#         'products': products,
#         'categories': categories,
#     }
#     return render(request, 'shop/index.html', context=context)

class ProductDetailView(View):
    def get(self, request, pk):
        product = get_object_or_404(Product, pk=pk)
        comments = Comment.objects.filter(product=product, is_negative=False)
        related_products = Product.objects.filter(category_id=product.category).exclude(id=product.id)

        context = {
            'product': product,
            'comments': comments,
            'related_products': related_products
        }

        return render(request, 'shop/detail.html', context=context)

# def product_detail(request, pk):
#     product = get_object_or_404(Product, pk=pk)
#     comments = Comment.objects.filter(product=product, is_negative=False)
#     related_products = Product.objects.filter(category_id=product.category).exclude(id=product.id)
#
#     context = {
#         'product': product,
#         'comments': comments,
#         'related_products': related_products
#     }
#
#     return render(request, 'shop/detail.html', context=context)

class OrderDetailView(View):
    def get(self, request, pk):
        product = get_object_or_404(Product, pk=pk)
        form = OrderForm(request.GET)
        if form.is_valid():
            full_name = request.GET.get('full_name')
            phone_number = request.GET.get('phone_number')
            quantity = int(request.GET.get('quantity'))
            if product.quantity >= quantity:
                product.quantity -= quantity
                messages.add_message(
                    request,
                    messages.SUCCESS,
                    message='Order successful sent'
                )
                order = Order.objects.create(
                    full_name=full_name,
                    phone_number=phone_number,
                    quantity=quantity,
                    product=product
                )
                order.save()
                product.save()
            else:
                messages.add_message(
                    request,
                    messages.ERROR,
                    message='Something with sent...'
                )
        else:
            form = OrderForm()
        connect = {
            'form': form,
            'product': product
        }

        return render(request, 'shop/detail.html', connect)





# def order_detail(request, pk):
#     product = get_object_or_404(Product, pk=pk)
#     if request.method == 'GET':
#         form=OrderForm(request.GET)
#         if form.is_valid():
#             full_name = request.GET.get('full_name')
#             phone_number = request.GET.get('phone_number')
#             quantity = int(request.GET.get('quantity'))
#             if product.quantity >= quantity:
#                 product.quantity -= quantity
#                 messages.add_message(
#                     request,
#                     messages.SUCCESS,
#                     message='Order successful sent'
#                 )
#                 order = Order.objects.create(
#                     full_name=full_name,
#                     phone_number=phone_number,
#                     quantity=quantity,
#                     product=product
#                 )
#                 order.save()
#                 product.save()
#             else:
#                 messages.add_message(
#                     request,
#                     messages.ERROR,
#                     message='Something with sent...'
#                 )
#
#
#     else:
#         form = OrderForm()
#     connect = {
#         'form': form,
#         'product': product
#     }
#
#     return render(request, 'shop/detail.html', connect)

class CommentView(View):
    def get(self, request, pk):
        product = CommentModelForm(Product, id=pk)
        form = CommentModelForm()
        context = {
            'product': product,
            'form': form,
        }
        return render(request, 'shop/detail.html', context=context)

    def post(self, request, pk):
        comment_form = CommentModelForm(data=request.POST)
        product = get_object_or_404(Product, id=pk)
        if comment_form.is_valid():
            comment_form.save(commit=False)
            comment_form.product = product
            comment_form.save()
            return redirect('shop:product_detail', pk)
        else:
            return render(request, 'shop/detail.html', {'form': comment_form, 'product': product})




# def comment_view(request, pk):
#     product = get_object_or_404(Product, id=pk)
#     form = CommentModelForm()
#     if request.method == 'POST':
#         form = CommentModelForm(request.POST)
#         if form.is_valid():
#             comment = form.save(commit=False)
#             comment.product = product
#             comment.save()
#             return redirect('shop:product_detail', pk)
#     context = {
#         'product': product,
#         'form': form,
#     }
#     return render(request, 'shop/detail.html', context=context)




class ProductCreateView(LoginRequiredMixin, View):

    def get(self, request, *args, **kwargs):
        form = ProductModelForm()
        context = {
            'form': form,
            'action': 'Create New'
        }
        return render(request, 'shop/create.html', context)

    def post(self, request, *args, **kwargs):
        form = ProductModelForm(data=request.POST, files=request.FILES)

        if form.is_valid():
            form.save()
            return redirect('shop:products')

        context = {
            'form': form,
            'action': 'Create New'
        }
        return render(request, 'shop/create.html', context)

# @login_required
# def product_create(request):
#     # form = ProductModelForm()
#     if request.method == 'POST':
#         form = ProductModelForm(request.POST, request.FILES)
#         if form.is_valid():
#             form.save()
#             return redirect('shop:products')
#     else:
#         form = ProductModelForm()
#     context = {
#         'form': form,
#         'action': 'Create New'
#     }
#     return render(request, 'shop/create.html', context=context)


class ProductDeleteView(View):
    def post(self, request, pk):
        product = get_object_or_404(Product, id=pk)
        product.delete()
        return redirect('shop:products')

# def product_delete(request, pk):
#     try:
#         product = Product.objects.get(id=pk)
#         product.delete()
#         return redirect('shop:products')
#     except Product.DoesNotExists as e:
#         print(e)



class ProductEditView(View):
    def get(self, request, pk):
        product = get_object_or_404(Product, id=pk)

shop/templates/shop/base/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en" xmlns="http://www.w3.org/1999/html">
<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no"/>
    <meta name="description" content=""/>
    <meta name="author" content=""/>
    <title>{% block title %}{% endblock %}</title>

    <!-- Favicon-->
    <link rel="icon" type="image/x-icon" href="{% static 'shop/assets/favicon.ico' %}"/>
    <!-- Bootstrap icons-->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css" rel="stylesheet"/>
    <!-- Core theme CSS (includes Bootstrap)-->
    <link href="{% static 'shop/css/styles.css' %}" rel="stylesheet"/>
</head>
<body>
<!-- Navigation-->
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <div class="container px-4 px-lg-5">
        <a class="navbar-brand" href="{% url 'shop:products' %}">Apelsin</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"><span
                class="navbar-toggler-icon"></span></button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0 ms-lg-4">
                <li class="nav-item"><a class="nav-link active" aria-current="page" href="{% url 'shop:products' %}">Home</a>
                </li>
                <li class="nav-item"><a class="nav-link" href="#!">About</a></li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" id="navbarDropdown" href="#" role="button"
                       data-bs-toggle="dropdown" aria-expanded="false">Categories</a>
                    <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                        <li><a class="dropdown-item" href="{% url 'shop:products' %}">All Products</a></li>
                        <li>
                            <hr class="dropdown-divider"/>
                        </li>
                        {% for category in categories %}
                            <li>
                                <a class="dropdown-item"
                                   href="{% url 'shop:products_of_category' category.id %}">{{ category.title }}</a>
                            </li>
                        {% endfor %}

                    </ul>
                </li>
            </ul>
            <form class="d-flex">
                <input type="text" name="q" class="form-contro">
                <button class="btn btn-outline-dark" type="submit">
                    <i class="bi-search-fill me-1"></i>
                    Search

                </button>
            </form>

            {% if user.is_authenticated %}
                <div style="margin-left: 14px">
                    <a href="{% url 'user:logout_page' %}">
                            <button type="button" class="btn btn-primary"> Logout </button>
                    </a>
                </div>
                <div style="margin-left: 20px">
                    <h3>{{ user.email }}</h3>
                </div>
            {% else %}
                <div style="margin-left: 14px">
                    <a href="{% url 'user:login_page' %}">
                            <button type="button" class="btn btn-primary"> Login </button>
                    </a>
                </div>

                <div style="margin-left: 14px">
                    <a href="#">
                            <button type="button" class="btn btn-primary"> Register </button>
                    </a>
                </div>
            {% endif %}
        </div>
    </div>
</nav>
<!-- Header-->
{% block index_content %}
{% endblock %}

{% block detail_content %}
{% endblock %}
<!-- Footer-->
<footer class="py-5 bg-dark">
    <div class="container"><p class="m-0 text-center text-white">Copyright &copy; Your Website 2023</p></div>
</footer>
<!-- Bootstrap core JS-->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"></script>
<!-- Core theme JS-->
<script src="{% static 'shop/js/scripts.js' %}"></script>
</body>
</html>