config/urls.py
from django.conf.urls.static import static
from django.conf import settings
from django.contrib import admin
from django.urls import path, include

import user

urlpatterns = [
    path('admin/', admin.site.urls),
    path('apelsin/', include('shop.urls'), name='shop'),
    path('user/', include('user.urls'), name='user'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

shop/urls.py
from django.urls import path, include
from shop import views

app_name = 'shop'


urlpatterns = [
    path('', views.IndexView.as_view(), name='products'),
    path('detail/<int:pk>/', views.ProductDetailView.as_view(), name='product_detail'),
    path('category-detail/<int:category_id>/', views.IndexView.as_view(), name='products_of_category'),
    path('order-detail/<int:pk>/save/', views.OrderDetailView.as_view(), name = 'order_detail'),
    path('create-product/', views.ProductCreateView.as_view(), name='product_create'),
    path('delete-product/<int:pk>/', views.ProductDeleteView.as_view(), name='product_delete'),
    path('edit-product/<int:pk>/', views.ProductEditView.as_view(), name='product_edit'),
    path('product-comments/<int:pk>/', views.CommentView.as_view(), name='comment_view'),
]

shop/models.py
from tkinter.constants import CASCADE

from django.db import models
from decimal import Decimal
from phonenumber_field.modelfields import PhoneNumberField



# Create your models here.


class BaseModel(models.Model):
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    my_order = models.PositiveIntegerField(default=0, blank=False, null=True)

    class Meta:
        ordering = ['my_order']
        abstract = True


class Category(BaseModel):
    title = models.CharField(max_length=100, unique=True)

    def __str__(self):
        return self.title

    class Meta:
        ordering = ['my_order']
        verbose_name = 'Category'
        verbose_name_plural = 'Categories'


class Product(BaseModel):

    class RatingChoise(models.IntegerChoices):
        ONE = 1
        TWO = 2
        THREE = 3
        FOUR = 4
        FIVE = 5

    name = models.CharField(max_length=255)
    description = models.TextField(null=True, blank=True)
    price = models.DecimalField(max_digits=14, decimal_places=2)
    discount = models.PositiveIntegerField(default=0)
    image = models.ImageField(upload_to='media/product/')
    category = models.ForeignKey(Category, on_delete=models.SET_NULL, related_name='products', null=True, blank=True)
    quantity = models.PositiveIntegerField(default=1, null=True, blank=True)
    rating = models.PositiveIntegerField(choices=RatingChoise.choices, default=RatingChoise.FIVE.value)


    @property
    def get_absolute_url(self):
        return self.image.url

    @property
    def discounted_price(self):
        if self.discount > 0:
            self.price = Decimal(self.price)*Decimal(1-self.discount / 100)
        return Decimal(self.price).quantize(Decimal('0.001'))

    def __str__(self):
        return self.name

    class Meta:
        ordering = ['my_order']
        verbose_name = 'Product'
        verbose_name_plural = 'Products'


class Order(BaseModel):
    full_name = models.CharField(max_length=255, null=True, blank=True)
    phone_number = PhoneNumberField(region="UZ")
    quantity = models.PositiveIntegerField(default=1)
    product = models.ForeignKey(Product, on_delete=models.SET_NULL, null=True, blank=True)

    def __str__(self):
        return f'{self.full_name} => {self.phone_number}'


class Comment(BaseModel):
    name = models.CharField(max_length=255, null=True, blank=True)
    email = models.EmailField()
    content = models.TextField()
    product = models.ForeignKey(Product, on_delete=models.CASCADE, related_name='comments', null=True, blank=True)

    is_negative = models.BooleanField(default=False)

    def __str__(self):
        return f"{self.name} => {self.created_at}"

    class Meta:
        ordering = ['my_order']
        #verbose_name = 'comment'

shop/forms.py
from django import forms
from phonenumber_field.modelfields import PhoneNumberField

from shop.models import Comment, Product


class OrderForm(forms.Form):
    full_name = forms.CharField()
    phone_number = PhoneNumberField(region='UZ')
    quantity = forms.IntegerField()


class ProductModelForm(forms.ModelForm):
    class Meta:
        model = Product
        fields = '__all__'
        # exclude = ()

class CommentModelForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = '__all__'

shop/views.py
from itertools import product
from lib2to3.fixes.fix_input import context
from typing import Optional

from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import render, get_object_or_404, redirect
from django.views import View

from shop.models import Product, Order, Category, Comment
from shop.forms import OrderForm, CommentModelForm, ProductModelForm


# Create your views here.
class IndexView(View):

    def get(self, request, category_id: Optional[int] = None, *args, **kwargs):
        search_query = request.GET.get('q', '')
        filter_type = request.GET.get('filter', '')
        categories = Category.objects.all()
        if category_id:
            if filter_type == 'expensive':
                products = Product.objects.filter(category_id=category_id).order_by('-price')
            elif filter_type == 'cheap':
                products = Product.objects.filter(category_id=category_id).order_by('price')
            elif filter_type == 'rating':
                products = Product.objects.filter(category_id=category_id, rating__gte=4).order_by('-rating')

            else:
                products = Product.objects.filter(category_id=category_id)

        else:
            if filter_type == 'expensive':
                products = Product.objects.all().order_by('-price')
            elif filter_type == 'cheap':
                products = Product.objects.all().order_by('price')
            elif filter_type == 'rating':
                products = Product.objects.filter(rating__gte=3).order_by('-rating')

            else:
                products = Product.objects.all()

        if search_query:
            products = Product.objects.filter(name__icontains=search_query)

        context = {
            'products': products,
            'categories': categories,
        }
        return render(request, 'shop/index.html', context=context)

# def index(request, category_id: Optional[int] = None):
#     search_query = request.GET.get('q', '')
#     filter_type = request.GET.get('filter', '')
#     categories = Category.objects.all()
#     if category_id:
#         if filter_type == 'expensive':
#             products = Product.objects.filter(category_id=category_id).order_by('-price')
#         elif filter_type == 'cheap':
#             products = Product.objects.filter(category_id=category_id).order_by('price')
#         elif filter_type == 'rating':
#             products = Product.objects.filter(category_id=category_id, rating__gte=4).order_by('-rating')
#
#         else:
#             products = Product.objects.filter(category_id=category_id)
#
#     else:
#         if filter_type == 'expensive':
#             products = Product.objects.all().order_by('-price')
#         elif filter_type == 'cheap':
#             products = Product.objects.all().order_by('price')
#         elif filter_type == 'rating':
#             products = Product.objects.filter(rating__gte=3).order_by('-rating')
#
#         else:
#             products = Product.objects.all()
#
#     if search_query:
#         products = Product.objects.filter(name__icontains=search_query)
#
#
#     context = {
#         'products': products,
#         'categories': categories,
#     }
#     return render(request, 'shop/index.html', context=context)

class ProductDetailView(View):
    def get(self, request, pk):
        product = get_object_or_404(Product, pk=pk)
        comments = Comment.objects.filter(product=product, is_negative=False)
        related_products = Product.objects.filter(category_id=product.category).exclude(id=product.id)

        context = {
            'product': product,
            'comments': comments,
            'related_products': related_products
        }

        return render(request, 'shop/detail.html', context=context)

# def product_detail(request, pk):
#     product = get_object_or_404(Product, pk=pk)
#     comments = Comment.objects.filter(product=product, is_negative=False)
#     related_products = Product.objects.filter(category_id=product.category).exclude(id=product.id)
#
#     context = {
#         'product': product,
#         'comments': comments,
#         'related_products': related_products
#     }
#
#     return render(request, 'shop/detail.html', context=context)

class OrderDetailView(View):
    def get(self, request, pk):
        product = get_object_or_404(Product, pk=pk)
        form = OrderForm(request.GET)
        if form.is_valid():
            full_name = request.GET.get('full_name')
            phone_number = request.GET.get('phone_number')
            quantity = int(request.GET.get('quantity'))
            if product.quantity >= quantity:
                product.quantity -= quantity
                messages.add_message(
                    request,
                    messages.SUCCESS,
                    message='Order successful sent'
                )
                order = Order.objects.create(
                    full_name=full_name,
                    phone_number=phone_number,
                    quantity=quantity,
                    product=product
                )
                order.save()
                product.save()
            else:
                messages.add_message(
                    request,
                    messages.ERROR,
                    message='Something with sent...'
                )
        else:
            form = OrderForm()
        connect = {
            'form': form,
            'product': product
        }

        return render(request, 'shop/detail.html', connect)





# def order_detail(request, pk):
#     product = get_object_or_404(Product, pk=pk)
#     if request.method == 'GET':
#         form=OrderForm(request.GET)
#         if form.is_valid():
#             full_name = request.GET.get('full_name')
#             phone_number = request.GET.get('phone_number')
#             quantity = int(request.GET.get('quantity'))
#             if product.quantity >= quantity:
#                 product.quantity -= quantity
#                 messages.add_message(
#                     request,
#                     messages.SUCCESS,
#                     message='Order successful sent'
#                 )
#                 order = Order.objects.create(
#                     full_name=full_name,
#                     phone_number=phone_number,
#                     quantity=quantity,
#                     product=product
#                 )
#                 order.save()
#                 product.save()
#             else:
#                 messages.add_message(
#                     request,
#                     messages.ERROR,
#                     message='Something with sent...'
#                 )
#
#
#     else:
#         form = OrderForm()
#     connect = {
#         'form': form,
#         'product': product
#     }
#
#     return render(request, 'shop/detail.html', connect)

class CommentView(View):
    def get(self, request, pk):
        product = CommentModelForm(Product, id=pk)
        form = CommentModelForm()
        context = {
            'product': product,
            'form': form,
        }
        return render(request, 'shop/detail.html', context=context)

    def post(self, request, pk):
        comment_form = CommentModelForm(data=request.POST)
        product = get_object_or_404(Product, id=pk)
        if comment_form.is_valid():
            comment_form.save(commit=False)
            comment_form.product = product
            comment_form.save()
            return redirect('shop:product_detail', pk)
        else:
            return render(request, 'shop/detail.html', {'form': comment_form, 'product': product})




# def comment_view(request, pk):
#     product = get_object_or_404(Product, id=pk)
#     form = CommentModelForm()
#     if request.method == 'POST':
#         form = CommentModelForm(request.POST)
#         if form.is_valid():
#             comment = form.save(commit=False)
#             comment.product = product
#             comment.save()
#             return redirect('shop:product_detail', pk)
#     context = {
#         'product': product,
#         'form': form,
#     }
#     return render(request, 'shop/detail.html', context=context)




class ProductCreateView(LoginRequiredMixin, View):

    def get(self, request, *args, **kwargs):
        form = ProductModelForm()
        context = {
            'form': form,
            'action': 'Create New'
        }
        return render(request, 'shop/create.html', context)

    def post(self, request, *args, **kwargs):
        form = ProductModelForm(data=request.POST, files=request.FILES)

        if form.is_valid():
            form.save()
            return redirect('shop:products')

        context = {
            'form': form,
            'action': 'Create New'
        }
        return render(request, 'shop/create.html', context)

# @login_required
# def product_create(request):
#     # form = ProductModelForm()
#     if request.method == 'POST':
#         form = ProductModelForm(request.POST, request.FILES)
#         if form.is_valid():
#             form.save()
#             return redirect('shop:products')
#     else:
#         form = ProductModelForm()
#     context = {
#         'form': form,
#         'action': 'Create New'
#     }
#     return render(request, 'shop/create.html', context=context)


class ProductDeleteView(View):
    def post(self, request, pk):
        product = get_object_or_404(Product, id=pk)
        product.delete()
        return redirect('shop:products')

# def product_delete(request, pk):
#     try:
#         product = Product.objects.get(id=pk)
#         product.delete()
#         return redirect('shop:products')
#     except Product.DoesNotExists as e:
#         print(e)



class ProductEditView(View):
    def get(self, request, pk):
        product = get_object_or_404(Product, id=pk)

shop/templates/shop/create.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{ action }} Product</title>
    <link rel="icon" type="image/x-icon" href="{% static 'shop/assets/favicon.ico' %}"/>
    <!-- Bootstrap icons-->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css" rel="stylesheet"/>
    <!-- Core theme CSS (includes Bootstrap)-->
    <link href="{% static 'shop/css/styles.css' %}" rel="stylesheet"/>
    <script src="https://cdn.tailwindcss.com"></script>
</head>
<body class="bg-gray-100 py-10">
<div class="max-w-4xl mx-auto bg-white p-8 rounded-2xl shadow-lg">
    <h1 class="text-2xl font-bold text-gray-700 mb-6 text-center">{{ action }} New Product</h1>
    <form action="#" method="POST" class="space-y-6" enctype="multipart/form-data">
        <!-- Product Name -->
        {{ form }}
        <div class="text-center">
            <button
                    type="submit"
                    class="bg-green-500 hover:bg-green-600 text-white py-3 px-6 rounded-lg shadow-md focus:outline-none focus:ring focus:ring-green-300"
            >
                {{ action }} Product
            </button>
        </div>
        <div class="col-1">
            <a class="btn btn-outline-warning" href="{% url 'shop:products' %}"> Cancel </a>
        </div>
        {% csrf_token %}
    </form>
</div>
</body>
</html>

shop/templates/shop/detail.html
{% extends 'shop/base/base.html' %}
{% load static %}

{% block title %}
    Product Detail
{% endblock %}

{% block detail_content %}

    <section class="py-5">
        <div class="container px-4 px-lg-5 my-5">
            <div class="row gx-4 gx-lg-5 align-items-center">
                <div class="col-md-6"><img class="card-img-top mb-5 mb-md-0" width="400px" height="800px"
                                           src="{{ product.get_absolute_url }}" alt="..."/></div>
                <div class="col-md-6">
                    {% if user.is_authenticated %}
                        <div style="display: flex; gap:10px;">
                            <form method="POST" action="{% url 'shop:product_delete' product.id %}">
                                <button type="submit" class="btn btn-danger">Delete</button>
                                {% csrf_token %}
                            </form>


                            <button type="submit" class="btn btn-outline-primary">
                                <a href="{% url 'shop:product_edit' product.id %}">Edit</a>
                            </button>

                        </div>

                    {% endif %}
                    <div class="small mb-1"><h3>Stock : {{ product.quantity }}</h3></div>
                    <h1 class="display-5 fw-bolder">{{ product.name }}</h1>
                    <div class="fs-5 mb-5">
                        {% if product.discount > 0 %}
                            <span class="text-decoration-line-through">${{ product.price }}</span>
                            <span>${{ product.discounted_price }}</span>
                        {% else %}
                            <span>${{ product.price }}</span>
                        {% endif %}

                    </div>
                    <p class="lead">{{ product.description }}</p>
                    <div class="d-flex">
                        <form method="get" action="{% url 'shop:order_detail' product.id %}">
                            <div class="form-group">
                                <h2>Place an order</h2>
                            </div>
                            <div class="form-group mb-3">
                                <label for="formGroupExampleInput">Your name</label>
                                <input type="text" name="full_name" class="form-control" placeholder="Your name">
                            </div>
                            <div class="form-group mb-3">
                                <label for="formGroupExampleInput2">Your phone</label>
                                <input type="text" name="phone_number" class="form-control" placeholder="Your phone">
                            </div>
                            <div class="form-group mb-3">
                                <label for="formGroupExampleInput">Quantity</label>
                                <input type="number" name="quantity" class="form-control" placeholder="Quantity">
                            </div>


                            <div class="form-group mb-3">

                                <input type="submit" class="btn btn-success" value="Send">
                            </div>
                        </form>

                    </div>
                    <div>
                        {% for message in messages %}
                            {% if 'error' in message.tags %}
                                <li style="color: red">{{ message }}</li>
                            {% elif 'success' in message.tags %}
                                <li style="color: green">{{ message }}</li>
                            {% endif %}

                        {% endfor %}
                    </div>
                </div>
            </div>
        </div>
    </section>

    <div class="container mt-4 mb-4">
        <div class="row">
            <div class="col-12">
                <div class="text-center">
                    <h2>Latest comments({{ product.comments.count }})</h2>
                </div>
                {# comment logic here #}
                {% for comment in comments %}
                    <div class="media card p-4 mt-2">
                        <div class="media-body">
                            <h3 class="mt-0">{{ comment.full_name }} => {{ comment.created_at }}</h3>
                            {{ comment.content }}
                        </div>
                    </div>
                {% endfor %}
                {# end #}
            </div>

            <div class="col-8 offset-2 mt-5">

                <div class=" p-5">
                    <div class="text-center">
                        <h3>Add Comment</h3>
                    </div>

                    <form method="post" action="{% url 'shop:comment_view' product.id %}">
                        {% csrf_token %}
                        <div class="form-group mb-3">
                            <label for="formGroupExampleInput">Your name</label>
                            <input type="text" name="full_name" class="form-control" placeholder="Your name">
                        </div>
                        <div class="form-group mb-3">
                            <label for="formGroupExampleInput2">Your email</label>
                            <input type="email" name="email" class="form-control" placeholder="Your email">
                        </div>

                        <div class="form-group mb-3">
                            <label for="formGroupExampleInput2">Your comment</label>
                            <textarea name="content" class="form-control" id="" cols="30" rows="10"></textarea>
                        </div>

                        <div class="form-group mb-3">

                            <input type="submit" class="btn btn-success" value="Send">
                        </div>
                    </form>

                </div>

            </div>
        </div>
    </div>
    <!-- Related items section-->
    <section class="py-5 bg-light">
        <div class="container px-4 px-lg-5 mt-5">
            <h2 class="fw-bolder mb-4">Related products</h2>
            <div class="row gx-4 gx-lg-5 row-cols-2 row-cols-md-3 row-cols-xl-4 justify-content-center">
                {% for product in related_products %}
                    <div class="col mb-5">
                        <div class="card h-100">
                            <!-- Product image-->
                            <img class="card-img-top"
                                 src="{{ product.get_absolute_url }}" alt="..."/>
                            <!-- Product details-->
                            <div class="card-body p-4">
                                <div class="text-center">
                                    <!-- Product name-->
                                    <h5 class="fw-bolder">{{ product.name }}</h5>
                                    <!-- Product price-->
                                    {{ product.price }}
                                </div>
                            </div>
                            <!-- Product actions-->
                            <div class="card-footer p-4 pt-0 border-top-0 bg-transparent">
                                <div class="text-center"><a class="btn btn-outline-dark mt-auto"
                                                            href="{% url 'shop:product_detail' product.id %}">View
                                    product</a></div>


                            </div>
                        </div>
                    </div>
                {% endfor %}

            </div>
        </div>
    </section>
{% endblock %}

shop/templates/shop/index.html
{% extends 'shop/base/base.html' %}
{% load static %}

{% block title %}
    Apelsin
{% endblock %}

{% block index_content %}
    <header class="bg-dark py-5">
        <div class="container px-4 px-lg-5 my-5">
            <div class="text-center text-white">
                <h1 class="display-4 fw-bolder">Jasur's Online Shop</h1>
                <p class="lead fw-normal text-white-50 mb-0">With this shop hompeage template</p>
            </div>
        </div>
    </header>
    <!-- Section-->

    <div class="container mt-5">
        <div class="text-left">
            <h3>Filter by</h3>
        </div>
        <div class="row">
            <div class="col-1">
                <a class="btn btn-outline-dark mt-auto" href="?filter=expensive"> Expensive </a>
            </div>

            <div class="col-1">
                <a class="btn btn-outline-dark mt-auto" href="?filter=cheap"> Cheap </a>
            </div>

            <div class="col-1">
                <a class="btn btn-outline-dark mt-auto" href="?filter=rating"> Rating </a>
            </div>
            {% if user.is_authenticated %}
                <div class="col-1">
                    <a class="btn btn-outline-success" href="{% url 'shop:product_create' %}"> Add Product </a>
                </div>
            {% endif %}


        </div>
    </div>
    <section class="py-5">
        <div class="container px-4 px-lg-5 mt-5">
            <div class="row gx-4 gx-lg-5 row-cols-2 row-cols-md-3 row-cols-xl-4 justify-content-center">
                {% for product in products %}
                    <div class="col mb-5">
                        <div class="card h-100">
                            <!-- Sale badge-->
                            {% if product.discount > 0 %}
                                <div class="badge bg-dark text-white position-absolute"
                                     style="top: 0.5rem; right: 0.5rem">
                                    Sale
                                </div>
                            {% endif %}
                            <!-- Product image-->
                            <img class="card-img-top" src="{{ product.get_absolute_url }}" alt="..."/>
                            <!-- Product details-->
                            <div class="card-body p-4">
                                <div class="text-center">
                                    <!-- Product name-->
                                    <h5 class="fw-bolder">{{ product.name }}</h5>
                                    <!-- Product reviews-->
                                    <div class="d-flex justify-content-center small text-warning mb-2">
                                        {% with ''|center:product.rating as range %}
                                            {% for f in range %}
                                                <div class="bi-star-fill"></div>
                                            {% endfor %}
                                        {% endwith %}

                                    </div>
                                    <!-- Product price-->
                                    {% if product.discount > 0 %}
                                        <span class="text-muted text-decoration-line-through">${{ product.price }}</span>
                                    {% endif %}
                                    ${{ product.discounted_price }}
                                </div>
                            </div>
                            <!-- Product actions-->
                            <div class="card-footer p-4 pt-0 border-top-0 bg-transparent">
                                <div class="text-center"><a class="btn btn-outline-dark mt-auto"
                                                            href="{% url 'shop:product_detail' product.id %}">View
                                    product</a></div>


                            </div>
                        </div>
                    </div>
                {% endfor %}
            </div>
        </div>
    </section>
{% endblock %}